# Smart Card Configuration File
# Format: [ATR] followed by insert= and remove= script paths
# Comments start with # or ;

# Your main unlock/lock card
[3BE700FF8131FE454430382E32203655]
insert=./unlock.sh
remove=./lock.sh

# Revolut second card for password pasting
[3BFF13000010003101F1564011001900000000000000]
insert=./paste_pass.sh
remove=

# Postbank card for nothing
[3BFE1300001080351603528660C3A04A4345533332]


# You can add more cards as needed
# [ANOTHER_ATR_HERE]
# insert=./another_script.sh
# remove=./cleanup_script.sh
